//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI.PhoenixWeb.Inmate.UserControls {


    public partial class usrAlias{
        

   
        /// <summary>
        /// cstNames control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPICustomName cstNames;

        /// <summary>
        /// chkMaiden control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPICheckBox chkMaiden;

        /// <summary>
        /// cmdAddAlias control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPIImageButton cmdAddAlias;

        /// <summary>
        /// cmdClearAlias control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPIImageButton cmdClearAlias;

        /// <summary>
        /// grdAlias control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPIGrid grdAlias;

        /// <summary>
        /// lblaliasesnicknmes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPILabel lblaliasesnicknmes;

        /// <summary>
        /// lblAliasNames control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPILabel lblAliasNames;
 }
}
