//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI.PhoenixWeb.Inmate.UserControls {


    public partial class usrAddresses{
        

   
        /// <summary>
        /// lblAddress control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPILabel lblAddress;

        /// <summary>
        /// adrAdditionalAddr control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Phoenix.WebControls.AddressCtrl adrAdditionalAddr;

        /// <summary>
        /// lblCity control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPILabel lblCity;

        /// <summary>
        /// custCSZ control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPICustomCSZ custCSZ;

        /// <summary>
        /// lupAddrCountry control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPICodedLookUp lupAddrCountry;

        /// <summary>
        /// lblType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPILabel lblType;

        /// <summary>
        /// cddType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPICodedDropDownList cddType;

        /// <summary>
        /// lblTelephone control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPILabel lblTelephone;

        /// <summary>
        /// custAddressPhone1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPICustomPhone custAddressPhone1;

        /// <summary>
        /// custAddressPhone2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPICustomPhone custAddressPhone2;

        /// <summary>
        /// Kpilabel2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPILabel Kpilabel2;

        /// <summary>
        /// dtcDeleteDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPIDateChooser dtcDeleteDate;

        /// <summary>
        /// cmdAddAddress control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPIImageButton cmdAddAddress;

        /// <summary>
        /// cmdClearAddress control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPIImageButton cmdClearAddress;

        /// <summary>
        /// grdAddress control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPIGrid grdAddress;
 }
}
