//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI.PhoenixWeb.Inmate.UserControls {
    
    
    public partial class usrMedicalMain {
        
        /// <summary>
        /// lblPrimaryDoctor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPILabel lblPrimaryDoctor;
        
        /// <summary>
        /// lupPrimaryDoctor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPICodedLookUp lupPrimaryDoctor;
        
        /// <summary>
        /// lblOfficeLocation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPILabel lblOfficeLocation;
        
        /// <summary>
        /// lblPhone control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPILabel lblPhone;
        
        /// <summary>
        /// txtOfficeLocation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPITextBox txtOfficeLocation;
        
        /// <summary>
        /// cusHeaderPhone control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPICustomPhone cusHeaderPhone;
        
        /// <summary>
        /// lblFlag control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPILabel lblFlag;
        
        /// <summary>
        /// lblLstMedvisit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPILabel lblLstMedvisit;
        
        /// <summary>
        /// dttmVisitDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPIDateTime dttmVisitDate;
        
      
        
       
        
        /// <summary>
        /// cddFlag control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPICodedDropDownList cddFlag;
        
        /// <summary>
        /// lblBldPresure control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPILabel lblBldPresure;
        
        /// <summary>
        /// txtBloodPressure1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPITextBox txtBloodPressure1;
        
        /// <summary>
        /// txtBloodPressure2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPITextBox txtBloodPressure2;
        
        /// <summary>
        /// lblPulse control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPILabel lblPulse;
        
        /// <summary>
        /// txtPulse control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPITextBox txtPulse;
        
        /// <summary>
        /// lblComment control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPILabel lblComment;
        
        /// <summary>
        /// lblHeight control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPILabel lblHeight;
        
        /// <summary>
        /// txtHeight control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPITextBox txtHeight;
        
        /// <summary>
        /// lblWeight control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPILabel lblWeight;
        
        /// <summary>
        /// txtWeight control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPITextBox txtWeight;
        
        /// <summary>
        /// txtComment control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPITextBox txtComment;
        
        /// <summary>
        /// lblReasonLstVisit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPILabel lblReasonLstVisit;
        
        /// <summary>
        /// txtReasonLstVisit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPITextBox txtReasonLstVisit;
        
        /// <summary>
        /// cmdAdd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPIImageButton cmdAdd;
        
        /// <summary>
        /// cmdClear control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPIImageButton cmdClear;
        
        /// <summary>
        /// btnNewVisit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPIButton btnNewVisit;
        
        /// <summary>
        /// cmdAddDoctor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPIImageButton cmdAddDoctor;
        
        /// <summary>
        /// cmdClearDoctor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPIImageButton cmdClearDoctor;
        
        /// <summary>
        /// grdFlag control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPIGrid grdFlag;
        
        /// <summary>
        /// lblMedicalVisits control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPILabel lblMedicalVisits;
        
        /// <summary>
        /// grdDoctor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPIGrid grdDoctor;
        
        /// <summary>
        /// lblTBTest control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPILabel lblTBTest;
        
        /// <summary>
        /// lblDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPILabel lblDate;
        
        /// <summary>
        /// dcTBTestDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPIDateChooser dcTBTestDate;
        
        /// <summary>
        /// lblMedicalNo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPILabel lblMedicalNo;
        
        /// <summary>
        /// NumCrtlMedicalNo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Phoenix.WebControls.NumberCtrl NumCrtlMedicalNo;
        
        /// <summary>
        /// lblResults control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPILabel lblResults;
        
        /// <summary>
        /// cddResults control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPI.Global.KPIWebControls.KPICodedDropDownList cddResults;
        
        /// <summary>
        /// hdnNameID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden hdnNameID;
        
        /// <summary>
        /// hdnMode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden hdnMode;
        
        /// <summary>
        /// hdnJurisId control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden hdnJurisId;
        
        /// <summary>
        /// hdnBookingid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden hdnBookingid;
    }
}
